// register 
### 
curl --location 'http://localhost:8080/users/register' \
--data-raw '{
    "full_name": "admin",
    "email": "admin@admin.com",
    "password": "admin"
}'


// register  
### 
curl --location 'http://localhost:8080/users/register' \
--data-raw '{
    "full_name": "user3",
    "email": "user3@user.com",
    "password": "secret"
}'

//login by user
###
curl --location 'http://localhost:8080/users/login' \
--data-raw '{
    "email": "user3@user.com",
    "password": "secret"
}'

//login by admin
###
curl --location 'http://localhost:8080/users/login' \
--data-raw '{
    "email": "admin@admin.com",
    "password": "admin"
}'


// register 
### 
curl --location 'http://localhost:8080/users/register' \
--data-raw '{
    "full_name": "admin",
    "email": "admin@admin.com",
    "password": "admin"
}'

// edit
###
curl --location --request PUT 'http://localhost:8080/users/edit' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyNDM4MzEsImlhdCI6MTc0MTE1NzQzMSwiaXNBZG1pbiI6ZmFsc2UsInVzZXJfaWQiOjF9.fbT1LDSqbh309rJRm0AvX23Oqh_C62JZp7mKeXtfEjw' \
--data-raw '{
    "full_name": "admin",
    "email": "admin@admin.com",
    "password": "admin",
    "is_admin": true
}'


//get all
###
curl --location --request GET 'http://localhost:8080/users/get-all-users?page=1&limit=5' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyNDM4MzEsImlhdCI6MTc0MTE1NzQzMSwiaXNBZG1pbiI6ZmFsc2UsInVzZXJfaWQiOjF9.fbT1LDSqbh309rJRm0AvX23Oqh_C62JZp7mKeXtfEjw' \

