// create
###
curl --location --request POST 'https://api.mujahid-dev.my.id/users/transaction/create' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyNDE4ODUsImlhdCI6MTc0MTE1NTQ4NSwiaXNBZG1pbiI6ZmFsc2UsInVzZXJfaWQiOjJ9.MhQ-FjC3PtsON3xOJc-AAb8HAf0B894FDAVLe37qjCI' \
--header 'Content-Type: application/json' \
--data-raw '{
  "item"         :   "Meja Kayu",
  "unit"         :    2
}'


// getall
###
curl --location --request GET 'https://api.mujahid-dev.my.id/users/transaction/get-all?page=1&limit=8' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyNDE4ODUsImlhdCI6MTc0MTE1NTQ4NSwiaXNBZG1pbiI6ZmFsc2UsInVzZXJfaWQiOjJ9.MhQ-FjC3PtsON3xOJc-AAb8HAf0B894FDAVLe37qjCI' \


// update status pay
###
curl --location --request PUT 'https://api.mujahid-dev.my.id/users/transaction/9?action=pay' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyNDE4ODUsImlhdCI6MTc0MTE1NTQ4NSwiaXNBZG1pbiI6ZmFsc2UsInVzZXJfaWQiOjJ9.MhQ-FjC3PtsON3xOJc-AAb8HAf0B894FDAVLe37qjCI' \
--header 'Content-Type: application/json' \


// update status cancel
###
curl --location --request PUT 'https://api.mujahid-dev.my.id/users/transaction/8?action=cancel' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyNDE4ODUsImlhdCI6MTc0MTE1NTQ4NSwiaXNBZG1pbiI6ZmFsc2UsInVzZXJfaWQiOjJ9.MhQ-FjC3PtsON3xOJc-AAb8HAf0B894FDAVLe37qjCI' \
--header 'Content-Type: application/json' \

// get by status failed
###
curl --location GET 'https://api.mujahid-dev.my.id/users/transaction/get?status=Failed' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyNDE4ODUsImlhdCI6MTc0MTE1NTQ4NSwiaXNBZG1pbiI6ZmFsc2UsInVzZXJfaWQiOjJ9.MhQ-FjC3PtsON3xOJc-AAb8HAf0B894FDAVLe37qjCI' \


// get by status paid
###
curl --location GET 'https://api.mujahid-dev.my.id/users/transaction/get?status=Paid' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyNDE4ODUsImlhdCI6MTc0MTE1NTQ4NSwiaXNBZG1pbiI6ZmFsc2UsInVzZXJfaWQiOjJ9.MhQ-FjC3PtsON3xOJc-AAb8HAf0B894FDAVLe37qjCI' \


// update status received admin
###
curl --location --request PUT 'https://api.mujahid-dev.my.id/users/transaction/admin/9' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyMzE1MjgsImlhdCI6MTc0MTE0NTEyOCwiaXNBZG1pbiI6dHJ1ZSwidXNlcl9pZCI6MX0.DaeZ5pm04k-Ztzj4ko_-W2NYOfyC-MXtUWx3n0Tu7eY' \
--header 'Content-Type: application/json' \








